// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'doc',
        id: 'gettingstarted/index',
      },
      items: [{type: 'autogenerated', dirName: 'gettingstarted'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [{type: 'autogenerated', dirName: 'concepts'}],
    },
    {
      type: 'category',
      label: 'Blocks',
      link: {
        type: 'doc',
        id: 'blocks/index',
      },
      items: [{type: 'autogenerated', dirName: 'blocks'}],
    },
    {
      type: 'category',
      label: 'Items',
      link: {
        type: 'doc',
        id: 'items/index',
      },
      items: [{type: 'autogenerated', dirName: 'items'}],
    },
    {
      type: 'category',
      label: 'Networking',
      link: {
        type: 'doc',
        id: 'networking/index',
      },
      items: [{type: 'autogenerated', dirName: 'networking'}],
    },
    {
      type: 'category',
      label: 'Block Entities',
      link: {
        type: 'doc',
        id: 'blockentities/index',
      },
      items: [{type: 'autogenerated', dirName: 'blockentities'}],
    },
    {
      type: 'category',
      label: 'Game Effects',
      items: [{type: 'autogenerated', dirName: 'gameeffects'}],
    },
    {
      type: 'category',
      label: 'Data Storage',
      items: [{type: 'autogenerated', dirName: 'datastorage'}],
    },
    {
      type: 'category',
      label: 'Graphical User Interfaces',
      items: [{type: 'autogenerated', dirName: 'gui'}],
    },
    {
      type: 'category',
      label: 'Rendering',
      items: [{type: 'autogenerated', dirName: 'rendering'}],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
    {
      type: 'category',
      label: 'Data Generation',
      link: {
        type: 'doc',
        id: 'datagen/index',
      },
      items: [{type: 'autogenerated', dirName: 'datagen'}],
    },
    {
      type: 'category',
      label: 'Miscellaneous Features',
      items: [{type: 'autogenerated', dirName: 'misc'}],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      items: [{type: 'autogenerated', dirName: 'advanced'}],
    },
    {
      type: 'category',
      label: 'Legacy Versions',
      items: [{type: 'autogenerated', dirName: 'legacy'}],
    },
  ],
};

module.exports = sidebars;
